currency = "USD"
default_view = "default"
api = "coingecko"
colorscheme = "synthwave"
refresh_rate = 60
cache_dir = "/tmp"

[shortcuts]
  "$" = "last_page"
  "%" = "sort_column_percent_holdings"
  "+" = "show_price_alert_add_menu"
  "/" = "open_search"
  0 = "first_page"
  1 = "sort_column_1h_change"
  2 = "sort_column_24h_change"
  3 = "sort_column_30d_change"
  7 = "sort_column_7d_change"
  "<" = "scroll_left"
  ">" = "scroll_right"
  "?" = "help"
  A = "toggle_price_alerts"
  C = "show_currency_convert_menu"
  E = "show_portfolio_edit_menu"
  F = "toggle_show_favorites"
  F1 = "help"
  F5 = "refresh"
  G = "move_to_page_last_row"
  H = "move_to_page_visible_first_row"
  L = "move_to_page_visible_last_row"
  M = "move_to_page_visible_middle_row"
  O = "open_link"
  P = "toggle_portfolio"
  Q = "quit_view"
  "[" = "previous_chart_range"
  "\\" = "toggle_table_fullscreen"
  "]" = "next_chart_range"
  a = "sort_column_available_supply"
  "alt+down" = "sort_column_desc"
  "alt+left" = "sort_left_column"
  "alt+right" = "sort_right_column"
  "alt+up" = "sort_column_asc"
  b = "sort_column_balance"
  c = "show_currency_convert_menu"
  "ctrl+C" = "quit"
  "ctrl+R" = "refresh"
  "ctrl+S" = "save"
  "ctrl+c" = "quit"
  "ctrl+d" = "page_down"
  "ctrl+f" = "open_search"
  "ctrl+j" = "enlarge_chart"
  "ctrl+k" = "shorten_chart"
  "ctrl+n" = "next_page"
  "ctrl+p" = "previous_page"
  "ctrl+r" = "refresh"
  "ctrl+s" = "save"
  "ctrl+u" = "page_up"
  down = "move_down"
  e = "show_portfolio_edit_menu"
  end = "move_to_page_last_row"
  enter = "toggle_row_chart"
  esc = "quit_view"
  f = "toggle_favorite"
  g = "move_to_page_first_row"
  h = "previous_page"
  home = "move_to_page_first_row"
  j = "move_down"
  k = "move_up"
  l = "next_page"
  left = "previous_page"
  m = "sort_column_market_cap"
  n = "sort_column_name"
  o = "open_link"
  p = "sort_column_price"
  pagedown = "page_down"
  pageup = "page_up"
  q = "quit_view"
  r = "sort_column_rank"
  right = "next_page"
  s = "sort_column_symbol"
  space = "toggle_favorite"
  t = "sort_column_total_supply"
  tab = "move_down_or_next_page"
  u = "sort_column_last_updated"
  up = "move_up"
  v = "sort_column_24h_volume"
  "{" = "first_chart_range"
  "|" = "toggle_chart_fullscreen"
  "}" = "last_chart_range"

[favorites]
  columns = ["rank", "name", "symbol", "price", "1h_change", "24h_change", "7d_change", "24h_volume", "market_cap", "available_supply", "total_supply", "last_updated"]
  names = ["Aave", "Augur", "Avalanche", "Axe", "Binance Coin", "Cardano", "Compound", "Ethereum", "Ethernity Chain", "Kusama", "Mobox", "PancakeSwap", "Polkadot", "STK", "Solana", "Synthetix Network Token"]
  symbols = []

[portfolio]
  columns = ["rank", "name", "symbol", "price", "holdings", "balance", "1h_change", "24h_change", "7d_change", "percent_holdings", "last_updated"]
  holdings = [["Acala", "5"], ["Astar", "780"], ["BENQI", "56"], ["Beethoven X", "1020"], ["Fantom", "11"], ["Gala", "46"], ["Karura", "10"], ["Kusama", "0.4"], ["Moonriver", "2"], ["Polkadot", "21"], ["RMRK", "2"], ["Shiden Network", "103"], ["Spookyswap", "3.4"], ["The Sandbox", "9.997"]]

[price_alerts]
  alerts = [["Beethoven X", ">", "0.85", "once"], ["Beethoven X", ">", "0.9", "once"], ["Beethoven X", ">", "0.9", "once"], ["Tomb Shares", ">", "15000", "once"], ["Elrond", ">", "400", "once"], ["PancakeSwap", ">", "17", "once"], ["Elrond", ">", "450", "once"]]

[coinmarketcap]
  pro_api_key = ""

[table]
  columns = ["rank", "name", "symbol", "price", "1h_change", "24h_change", "7d_change", "24h_volume", "market_cap", "available_supply", "total_supply", "last_updated"]
  keep_row_focus_on_sort = false
